BB-1205: Cherry pick customizations from Cloudera
open-craft/configuration pull request #96
Opened 2019-05-09 16:43 UTC by giovannicimolin

This PR cherry picks a few customizations made to Cloudera's repo into our common branch.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

2019-05-13 03:39 UTC, pomegranited requested changes
@giovannicimolin In an attempt to make this diff much smaller, I'm trying to deploy the sandbox with this branch instead: [`jill/bb-1205-cloudera-cherry-picks`](https://github.com/open-craft/configuration/compare/opencraft-release/ironwood.1...jill/bb-1205-cloudera-cherry-picks):

My theory with the tracking-log-related commit goes something like this:
* We have a couple Ocim clients who are still storing data on SWIFT but need tracking logs on S3 for analytics.
* Our complex code drift allows us to store tracking logs on both SWIFT + S3, but we really only need them on S3.
* The `COMMON_OBJECT_STORE_LOG_SYNC_SCRIPT` symlink is what determines which script (aws or opencraft) gets run when the tracking logs are rotated.
* Both the [`aws`](https://github.com/open-craft/configuration/blob/jill/bb-1205-cloudera-cherry-picks/playbooks/roles/aws/tasks/main.yml#L88-L93) and [`openstack`](https://github.com/open-craft/configuration/blob/jill/bb-1205-cloudera-cherry-picks/playbooks/roles/openstack/tasks/main.yml#L46-L51) roles change that symlink to point to their own script.
*  If `OPENCRAFT_ENABLE_SWIFT_LOG_SYNC: true`, then let the swift syncing script be symlinked.

If it works, then you can just hard reset your branch to that branch, and it's ready to merge.

2019-05-13 03:39 UTC, pomegranited commented on playbooks/roles/common_vars/defaults/main.yml
> -COMMON_OBJECT_STORE_LOG_SYNC_ON_EXIT: "{{ COMMON_BIN_DIR }}/sync-logs-on-exit"
We still need this line, since this is part of https://github.com/open-craft/configuration/commit/1e88d37ec73ae3100384671b08b1e653f812b522.

(Removal of this line caused sandbox configuration failure for [Appserver #9](https://console.opencraft.com/instance/15370/edx-appserver/9701/).

But see my note below -- we might be able to reduce the drift here with a simpler change.

2019-05-13 03:39 UTC, pomegranited commented on playbooks/openedx_native.yml
> +    DEPLOY_DEMO_ROLE: true
Could you rename this to `DEMO_ROLE_ENABLED` instead, to sit in line with `JOURNALS_ENABLED` and `EDX_NOTES_API_ENABLED` above?

2019-05-13 14:28 UTC, giovannicimolin commented
@pomegranited I'll wait for the Appserver to spawn and hard reset my branch to yours if everything is ok. Thanks for helping me with this! :grin:

2019-05-14 23:54 UTC, pomegranited approved these changes
:+1: Thanks @giovannicimolin !

- [x] I tested this on two Ocim servers:
   1. With SWIFT + S3 tracking logs enabled, and the demo role disabled (see config notes in PR).
      Verified that the demo course was not created, and that tracking logs were synced to the S3 bucket, and all the django storage was stored in SWIFT containers.
   1. With a standard production beta server and no extra configuration.
      Verified that the demo course was created, and that tracking logs and other django storage use S3.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation

2019-05-15 13:28 UTC, merged